// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../common/js/bitpug/Game.js', ['bp.Game'], ['bp.controllers.GameController', 'bp.ui.Menu', 'goog.net.XhrIo']);
goog.addDependency('../../../common/js/bitpug/controllers/GameController.js', ['bp.controllers.GameController'], ['bp.controllers.KeyController', 'bp.controllers.PointController', 'bp.controllers.PugController', 'bp.controllers.RainController', 'bp.controllers.RegistryController', 'bp.ui.ActionMsg', 'bp.ui.Clouds', 'bp.ui.StatDisplay', 'goog.dom', 'goog.events', 'goog.events.EventTarget', 'goog.ui.Component']);
goog.addDependency('../../../common/js/bitpug/controllers/KeyController.js', ['bp.controllers.KeyController'], ['bp.events.MainControl', 'goog.events.EventTarget']);
goog.addDependency('../../../common/js/bitpug/controllers/PointController.js', ['bp.controllers.PointController'], ['bp.events.ActionMsgEvent', 'goog.events']);
goog.addDependency('../../../common/js/bitpug/controllers/PugController.js', ['bp.controllers.PugController'], ['bp.controllers.RegistryController', 'bp.events.MainControl', 'bp.ui.PugPlayer']);
goog.addDependency('../../../common/js/bitpug/controllers/RainController.js', ['bp.controllers.RainController'], ['bp.events.PointCounter', 'bp.ui.RainDrop', 'goog.Timer', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.math', 'goog.math.Coordinate']);
goog.addDependency('../../../common/js/bitpug/controllers/RegistryController.js', ['bp.controllers.RegistryController'], ['goog.dom.classes']);
goog.addDependency('../../../common/js/bitpug/events/ActionMsgEvent.js', ['bp.events.ActionMsgEvent'], ['goog.events.Event']);
goog.addDependency('../../../common/js/bitpug/events/MainControl.js', ['bp.events.MainControl'], ['goog.events.Event']);
goog.addDependency('../../../common/js/bitpug/events/PointCounter.js', ['bp.events.PointCounter'], ['goog.events.Event']);
goog.addDependency('../../../common/js/bitpug/ui/ActionMsg.js', ['bp.ui.ActionMsg'], ['bp.events.ActionMsgEvent', 'goog.Timer', 'goog.ui.Component']);
goog.addDependency('../../../common/js/bitpug/ui/Clouds.js', ['bp.ui.Clouds'], ['goog.Timer', 'goog.ui.Component']);
goog.addDependency('../../../common/js/bitpug/ui/Menu.js', ['bp.ui.Menu'], ['goog.ui.Component']);
goog.addDependency('../../../common/js/bitpug/ui/PugPlayer.js', ['bp.ui.PugPlayer'], ['bp.events.ActionMsgEvent', 'goog.Timer', 'goog.dom.classes', 'goog.fx.Animation', 'goog.math', 'goog.style', 'goog.ui.Component']);
goog.addDependency('../../../common/js/bitpug/ui/RainDrop.js', ['bp.ui.RainDrop'], ['bp.ui.PugPlayer', 'goog.dom.classes', 'goog.style', 'goog.ui.Component']);
goog.addDependency('../../../common/js/bitpug/ui/StatDisplay.js', ['bp.ui.StatDisplay'], ['goog.Timer', 'goog.ui.Component']);
