// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../common/js/bitpug/Game.js', ['bitpug.Game'], ['bitpug.controllers.GameController']);
goog.addDependency('../../../common/js/bitpug/controllers/GameController.js', ['bitpug.controllers.GameController'], ['bitpug.controllers.KeyController', 'bitpug.controllers.PugController', 'bitpug.controllers.RegistryController', 'bitpug.ui.StatDisplay', 'goog.dom', 'goog.events', 'goog.events.EventTarget', 'goog.ui.Component']);
goog.addDependency('../../../common/js/bitpug/controllers/KeyController.js', ['bitpug.controllers.KeyController'], ['bitpug.events.MainControl', 'goog.events.EventTarget']);
goog.addDependency('../../../common/js/bitpug/controllers/PugController.js', ['bitpug.controllers.PugController'], ['bitpug.events.MainControl']);
goog.addDependency('../../../common/js/bitpug/controllers/RegistryController.js', ['bitpug.controllers.RegistryController'], ['goog.dom.classes']);
goog.addDependency('../../../common/js/bitpug/events/MainControl.js', ['bitpug.events.MainControl'], ['goog.events.Event']);
goog.addDependency('../../../common/js/bitpug/ui/StatDisplay.js', ['bitpug.ui.StatDisplay'], ['goog.Timer', 'goog.ui.Component']);
