// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../common/js/bitpug/Game.js', ['bitpug.Game'], ['bitpug.controllers.GameController', 'goog.net.XhrIo']);
goog.addDependency('../../../common/js/bitpug/controllers/GameController.js', ['bitpug.controllers.GameController'], ['bitpug.controllers.KeyController', 'bitpug.controllers.PugController', 'bitpug.controllers.RainController', 'bitpug.controllers.RegistryController', 'bitpug.ui.StatDisplay', 'goog.dom', 'goog.events', 'goog.events.EventTarget', 'goog.ui.Component']);
goog.addDependency('../../../common/js/bitpug/controllers/KeyController.js', ['bitpug.controllers.KeyController'], ['bitpug.events.MainControl', 'goog.events.EventTarget']);
goog.addDependency('../../../common/js/bitpug/controllers/PugController.js', ['bitpug.controllers.PugController'], ['bitpug.controllers.RegistryController', 'bitpug.events.MainControl', 'bitpug.ui.PugPlayer']);
goog.addDependency('../../../common/js/bitpug/controllers/RainController.js', ['bitpug.controllers.RainController'], ['bitpug.ui.RainDrop', 'goog.Timer', 'goog.math', 'goog.math.Coordinate']);
goog.addDependency('../../../common/js/bitpug/controllers/RegistryController.js', ['bitpug.controllers.RegistryController'], ['goog.dom.classes']);
goog.addDependency('../../../common/js/bitpug/events/MainControl.js', ['bitpug.events.MainControl'], ['goog.events.Event']);
goog.addDependency('../../../common/js/bitpug/ui/PugPlayer.js', ['bitpug.ui.PugPlayer'], ['goog.Timer', 'goog.dom.classes', 'goog.fx.Animation', 'goog.math', 'goog.style', 'goog.ui.Component']);
goog.addDependency('../../../common/js/bitpug/ui/RainDrop.js', ['bitpug.ui.RainDrop'], ['bitpug.ui.PugPlayer', 'goog.dom.classes', 'goog.style', 'goog.ui.Component']);
goog.addDependency('../../../common/js/bitpug/ui/StatDisplay.js', ['bitpug.ui.StatDisplay'], ['goog.Timer', 'goog.ui.Component']);
